services:
  postgresql:
    image: postgres:17
    container_name: postgresql
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"

  fastapi_app:
    build: .
    container_name: fastapi_app
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgresql
    env_file:
      - .env
