"""add user_id in short_urls

Revision ID: 6ebc884208d6
Revises: 04e36d9cd2da
Create Date: 2025-06-01 23:18:33.047813

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6ebc884208d6"
down_revision: Union[str, None] = "04e36d9cd2da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "short_urls", sa.Column("user_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "short_urls", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "short_urls", type_="foreignkey")
    op.drop_column("short_urls", "user_id")
    # ### end Alembic commands ###
