class AppException(Exception): ...


class URLNotFound(AppException): ...


class URLAccessDenied(AppException): ...


class URLInactive(AppException): ...


class URLExpired(AppException): ...


class URLGenerationFailed(AppException): ...


class UserAlreadyExists(AppException): ...


class InvalidCredentials(AppException): ...
